spring:
  application:
    name: currentaccount
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  hikari:
    connection-timeout: 20000
    minimum-idle: 2
    maximum-pool-size: 4
    idle-timeout: 10000
    max-lifetime: 9000000
  sql:
    init:
      platform: postgresql
      initialization-mode: never

  # Always validate the model against the schema.
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    open-in-view: false

  # Always run Flyway, never baseline on migrate (unless you know what you're doing)
  flyway:
    enabled: true
    baseline-on-migrate: false
